#! /usr/bin/env python

import sys
from MCTS import *
from sympy import sympify, symbols
from sympy.parsing.sympy_parser import parse_expr

def main(args):
    mcts = MCTS("x^2 + 4*x + 1", 50000)
    mcts.run()     

if __name__ == '__main__':
    main(sys.argv[1:])
