#! /usr/bin/env python

import sys
from MCTS import MCTS 
from ExpressionComponents import components
from ExpressionHandler import ExpressionHandler

def main(args):
    my_objective = [components[4], components[0], components[1]]
    handlerObject = ExpressionHandler()
    handlerObject.maxSolutionSize = 5
    handlerObject.objective = my_objective
    mcts = MCTS(handlerObject)
    #mcts.run()

if __name__ == '__main__':
    main(sys.argv[1:])

