#! /usr/bin/env python

import sys
from MCTS import *
from SolutionHandler import *
#from sympy import sympify, symbols
#from sympy.parsing.sympy_parser import parse_expr

def main(args):
    my_objective = [expansions[4], expansions[0], expansions[1]]
    handlerObject = ExpressionHandler()
    handlerObject.expansion_limit = 5
    handlerObject.objective = my_objective
    mcts = MCTS(handlerObject)
    #mcts.run()

if __name__ == '__main__':
    main(sys.argv[1:])

